name: 'Setup Bun with Cache'
description: 'Set up Bun and restore/cache dependencies'

inputs:
  bun-version:
    description: 'Bun version to use'
    required: true
    default: '1.3.2'

runs:
  using: 'composite'
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Restore dependencies cache
      id: cache-restore
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: bun-${{ runner.os }}-${{ hashFiles('bun.lockb') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Check if dependencies exist
      id: check-deps
      shell: bash
      run: |
        if [ -d "node_modules" ] && [ "$(ls -A node_modules)" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Install dependencies
      if: steps.check-deps.outputs.exists != 'true'
      shell: bash
      run: bun install --frozen-lockfile
